### ISSUE TITLE
What is the input I in N3AggregationBase?

### ISSUE THREAD

**Issue by weixmath** [visinf/n3net#6]
You said the input "I" is "Indexing tensor defining O potential neighbors for each query item". How can i construct this input? My xe is a tensor of 4*2048*12 and ye is a tensor of 4*2048*12, so the "I" is a tensor of 4*12*12, am i right? What are the elements of "I"?

**Comment by tobiasploetz** [comment]
Per batch, there are M query items in `y, ye` and N database items in `x, xe`. The index tensor I selects for each query item a set of O database items that should be used for neural nearest neighbour matching. That implies that every entry in I is an integer between 0 and N-1.

**Comment by weixmath** [comment]
Thank you ,my friend.  :+1:  nice job
